name: build

env: 
  MIX_TARGET: citron_rpi5
  
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Main
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.3
    - run: flutter --version

    - name: Deps
      run: mix deps.get

    - name: Compile
      run: mix compile --all-warnings --warnings-as-errors

    - name: Build
      run: mix firmware

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: can_client.fw
        path: _build/citron_rpi5_dev/nerves/images/can_client.fw
